### ISSUE TITLE
Coffin fails with Django >=1.8, Breaks CI Build

### ISSUE THREAD

**Issue by juancarlospaco** [amitu/importd#62]
- Coffin fails with Django >=1.8
- Breaks CI Build.
- Please see: https://travis-ci.org/amitu/importd/jobs/50173170
- Please see: https://travis-ci.org/amitu/importd/jobs/50173170#L267

I complains:
```python
 File "/home/travis/build/amitu/importd/.tox/py27-django18/lib/python2.7/site-packages/coffin/template/__init__.py", line 1, in <module>
    from django.template import (add_to_builtins
ImportError: cannot import name add_to_builtins
```

:disappointed:

**Comment by amitu** [comment]
Damn. It also breaks my djangothis project which relies on add_to_builtins. 

add_to_builtins is no django.template.base now. We have to wait for coffin to change their import path, probably an ImportError fallback.

**Comment by amitu** [comment]
Files bug with [django-jinja](https://github.com/niwibe/django-jinja/issues/92) and created [pull request](https://github.com/coffin/coffin/pull/87) for coffin. 

Will have to wait for those guys. I tried monkey patching things, but it did not fix all the issues.

**Comment by amitu** [comment]
Nopes. It is our fault. Starting 1.8 django has deprecated a bunch of settings, TEMPLATE_*, and replaced them all with TEMPLATES dict. 

Currently we are detecting if django_jinja/coffin is installed, in which case we auto configure TEMPALTE_* settings.

We either remove support for them, or make them use the new way.

Problem is that now since there is only one big dict, its not safe for us to overwrite/change it. It contains template locations, loaders, context processors etc. And one or another will be modified by most developers, meaning some dict will always be there. 

I am biased towards removing coffin/django_jinja support, and letting developers configure them. As we are not doing much value add, and developers have to do rather little to support it. 

What do you say?

**Comment by juancarlospaco** [comment]
Can be Coffin removed without losing Jinja ?
If removing is the safest way, we may...

**Comment by amitu** [comment]
Yep. Since django_jinja has better integration with django, I think we should prefer that one, and not have two different implementation for jinja.

How to remove it, let me see.

**Comment by juancarlospaco** [comment]
We should keep it clean, simple, readable..., 
if it have too many lines of weird hacks to make 1 feature works on the risk of the whole thing not working, 
its not worth it, some stuff are more friendly to integrate than others, we should point that way.

**Comment by SalahAdDin** [comment]
I have the same error when i try migrate my apps with --fake-initial

**Comment by amitu** [comment]
We will be removing coffin as part of #72, so closing this.
